###Users
GET http://localhost:8080/users HTTP/1.1

###Movie
GET http://localhost:8080/movies/1 HTTP/1.1

###Scores
GET http://localhost:8080/scores HTTP/1.1

###
PUT http://localhost:8080/scores/avaliar HTTP/1.1
content-type: application/json

{
    "userEmail": "ejsmao@hotmail.com",
	"movieId": 4,
	"value": 3
}

###Users
GET https://dsmovie-mecyo.herokuapp.com/users HTTP/1.1

###Movies
GET https://dsmovie-mecyo.herokuapp.com/movies HTTP/1.1

###Scores
GET https://dsmovie-mecyo.herokuapp.com/scores HTTP/1.1

###
PUT https://dsmovie-mecyo.herokuapp.com/scores/avaliar HTTP/1.1
content-type: application/json

{
    "userEmail": "jojao23@hotmail.com",
	"movieId": 1,
	"value": 1
}