###Users
GET http://localhost:8080/users HTTP/1.1

###Scores
GET http://localhost:8080/scores HTTP/1.1

###
PUT http://localhost:8080/scores/avaliar HTTP/1.1
content-type: application/json

{
    "userEmail": "jojo@hotmail.com",
	"movieId": 1,
	"value": 5
}

###Users
GET https://dsmovie-mecyo.herokuapp.com/users HTTP/1.1

###Scores
GET https://dsmovie-mecyo.herokuapp.com/scores HTTP/1.1

###
PUT https://dsmovie-mecyo.herokuapp.com/scores/avaliar HTTP/1.1
content-type: application/json

{
    "userEmail": "ejsmao@hotmail.com",
	"movieId": 1,
	"value": 3
}